-- MySQL Script generated by MySQL Workbench
-- Mon Nov 30 17:04:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema laba8
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laba8
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laba8` DEFAULT CHARACTER SET utf8 ;
USE `laba8` ;

-- -----------------------------------------------------
-- Table `laba8`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laba8`.`product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cost` INT NOT NULL,
  `amount` INT NOT NULL,
  `yearOfRelease` DATE NOT NULL,
  PRIMARY KEY (`idproduct`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
